// Static site builder — zero runtime dependencies.  src/ → site/
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { icon, ICONS } from './icons.mjs';
import { MOVES, RES, SIGS, STANCES, ATTRS, MODES } from './content.mjs';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const src = path.join(root, 'src'), out = path.join(root, 'site');
const SITE = JSON.parse(fs.readFileSync(path.join(root, 'site.config.json'), 'utf8'));

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const cp = (a, b) => { fs.mkdirSync(path.dirname(b), { recursive: true }); fs.copyFileSync(a, b); };
const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]);

// assets
for (const f of walk(path.join(src, 'assets'))) cp(f, path.join(out, path.relative(src, f)));

// generated icon map for client-side rendering
fs.writeFileSync(path.join(src, 'js/icons.js'), `/* generated by scripts/build.mjs — do not edit */\nwindow.DY=window.DY||{};DY.icons=${JSON.stringify(Object.fromEntries(Object.keys(ICONS).map(k => [k, icon(k, 'i', 24)])))};\n`);

fs.writeFileSync(path.join(src, 'js/content.js'), `/* generated by scripts/build.mjs from scripts/content.mjs — do not edit */\nwindow.DY=window.DY||{};DY.MOVES=${JSON.stringify(MOVES)};DY.RES=${JSON.stringify(RES)};DY.SIGS=${JSON.stringify(SIGS)};\n`);

// css bundle (order matters) + js copy, with content hash for cache-busting
const cssFiles = ['base', 'components', 'hero', 'sections', 'pages'].filter(n => fs.existsSync(path.join(src, 'css', n + '.css')));
const css = cssFiles.map(n => fs.readFileSync(path.join(src, 'css', n + '.css'), 'utf8')).join('\n');
const cssHash = crypto.createHash('md5').update(css).digest('hex').slice(0, 8);
fs.mkdirSync(path.join(out, 'css'), { recursive: true });
fs.writeFileSync(path.join(out, 'css/site.css'), css);
const jsHashes = {};
for (const f of fs.readdirSync(path.join(src, 'js'))) {
  const buf = fs.readFileSync(path.join(src, 'js', f));
  jsHashes[f] = crypto.createHash('md5').update(buf).digest('hex').slice(0, 8);
  cp(path.join(src, 'js', f), path.join(out, 'js', f));
}


const esc = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
const GEN = {
  moves: () => MOVES.map((m, i) => `<article class="move rv" id="move-${m.k.toLowerCase()}" style="--d:${(i % 2) * 60}ms"><header><span class="mv-ico">${icon(m.ico, 'i', 36)}</span><div><h3>${m.name}</h3><span class="caps">${m.line}</span></div></header><p>${m.desc}</p><div class="chips"><span class="tag">Energy · ${m.energy}</span><span class="tag tag--oxide">${m.gain}</span><span class="tag tag--trace">${m.risk}</span></div><dl><div><dt>Best when</dt><dd>${m.when}</dd></div><div><dt>Watch out</dt><dd>${m.watch}</dd></div></dl></article>`).join(''),
  resources: () => RES.map(r => `<div class="res-row rv"><span class="res-ico">${icon(r.k, 'i', 28)}</span><div><h3>${r.name}</h3><p>${r.def}</p><p class="muted">${r.more}</p></div><span class="tag">${r.range}</span></div>`).join(''),
  signatures: () => SIGS.map((g, i) => `<li class="sig rv" style="--d:${(i % 4) * 50}ms"><span class="tag tag--trace">${g.tag}</span><h3>${g.name}</h3><p>${g.desc}</p><code>${g.id}</code></li>`).join(''),
  stances: () => STANCES.map(s => `<li class="rv"><h3>${s[0]}</h3><p><span class="up">▲ ${s[1]}</span><span class="dn">▼ ${s[2]}</span></p></li>`).join(''),
  attrs: () => ATTRS.map(a => `<li class="rv"><b>${a[0]}</b><span>${a[1]}</span></li>`).join(''),
  modes: () => MODES.map(m => `<article class="mode rv frame panel"><span class="tag">${m.tag}</span><h3>${m.name}</h3><p>${m.desc}</p></article>`).join('')
};

// partials
const partial = (name) => {
  for (const d of ['partials', 'partials/_gen']) { const p = path.join(src, d, name + '.html'); if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8'); }
  throw new Error('missing partial ' + name);
};
let uid = 0;
function render(html, meta, depth = 0) {
  if (depth > 6) throw new Error('include depth');
  html = html.replace(/\{\{>\s*([\w-]+)\s*\}\}/g, (_, n) => render(partial(n).replaceAll('{{uid}}', 'u' + (++uid)), meta, depth + 1));
  html = html.replace(/\{\{gen:(\w+)\}\}/g, (_, n) => GEN[n]());
  html = html.replace(/\{\{icon:([\w-]+)(?::(\d+))?\}\}/g, (_, n, s) => { if (!ICONS[n]) throw new Error('missing icon ' + n); return icon(n, 'i', s ? +s : 24); });
  html = html.replace(/\{\{cur:([\w-]+)\}\}/g, (_, n) => meta.active === n ? ' aria-current="page"' : '');
  html = html.replace(/\{\{earlyaccess\}\}/g, () => SITE.earlyAccessEndpoint
    ? `<form class="ea frame panel" id="eaForm" data-endpoint="${SITE.earlyAccessEndpoint}" novalidate><label for="eaMail" class="caps muted">Early access list</label><div class="ea-row"><input id="eaMail" name="email" type="email" autocomplete="email" required placeholder="you@example.com" aria-describedby="eaMsg"><button class="btn btn--primary" type="submit">Notify me</button></div><p id="eaMsg" class="muted" role="status" style="margin:.7rem 0 0;font-size:.9rem">One email when operator slots open. No lists sold. Unsubscribe any time.</p></form>`
    : '');
  html = html.replace(/\{\{css\}\}/g, 'css/site.css?v=' + cssHash);
  html = html.replace(/\{\{js:([\w.-]+)\}\}/g, (_, n) => `js/${n}?v=${jsHashes[n] ?? 'x'}`);
  html = html.replace(/\{\{site\.(\w+)\}\}/g, (_, k) => SITE[k] ?? '');
  html = html.replace(/\{\{pagescripts\}\}/g, () => (meta.scripts ?? []).map(n => `<script src="js/${n}?v=${jsHashes[n] ?? 'x'}" defer></script>`).join('\n'));
  html = html.replace(/\{\{(title|description|canonical|ogimage|bodyclass|active)\}\}/g, (_, k) => meta[k] ?? '');
  return html;
}

const pages = fs.readdirSync(path.join(src, 'pages')).filter(f => f.endsWith('.html'));
const urls = [];
for (const f of pages) {
  let raw = fs.readFileSync(path.join(src, 'pages', f), 'utf8');
  const m = raw.match(/^<!--meta\s*([\s\S]*?)-->\s*/);
  if (!m) throw new Error('page missing meta: ' + f);
  const meta = JSON.parse(m[1]);
  raw = raw.slice(m[0].length);
  const slug = f === 'index.html' ? '' : f;
  meta.canonical = SITE.origin + '/' + slug;
  meta.ogimage = SITE.origin + '/assets/brand/og-image.png';
  meta.title = meta.title === 'DYADRYN' ? 'DYADRYN — Built from memory. Proven in battle. | AI Persona Arena' : meta.title + ' — DYADRYN';
  const full = render(`{{> head}}<body class="${meta.bodyclass ?? ''}">{{> header}}<main id="main">${raw}</main>{{> footer}}</body></html>`, meta);
  fs.writeFileSync(path.join(out, f), full);
  if (f !== '404.html') urls.push(SITE.origin + '/' + slug);
}

// robots (reserve rights: AI-training crawlers disallowed), sitemap, headers, manifest
const AI_BOTS = ['GPTBot', 'ChatGPT-User', 'OAI-SearchBot', 'CCBot', 'anthropic-ai', 'ClaudeBot', 'Claude-Web', 'Google-Extended', 'Applebot-Extended', 'Bytespider', 'PerplexityBot', 'Amazonbot', 'FacebookBot', 'meta-externalagent', 'cohere-ai', 'Diffbot', 'ImagesiftBot', 'omgili', 'Timpibot'];
fs.writeFileSync(path.join(out, 'robots.txt'), `# DYADRYN reserves all rights, including text-and-data-mining and AI-training rights (see /legal.html).\n${AI_BOTS.map(b => `User-agent: ${b}\nDisallow: /\n`).join('\n')}\nUser-agent: *\nAllow: /\n\nSitemap: ${SITE.origin}/sitemap.xml\n`);
fs.writeFileSync(path.join(out, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u => `  <url><loc>${u}</loc></url>`).join('\n')}\n</urlset>\n`);
fs.writeFileSync(path.join(out, '_headers'), `/*
  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  tdm-reservation: 1
  tdm-policy: ${SITE.origin}/legal.html#rights

/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable
/css/*
  Cache-Control: public, max-age=31536000, immutable
/js/*
  Cache-Control: public, max-age=31536000, immutable
`);
fs.writeFileSync(path.join(out, 'manifest.webmanifest'), JSON.stringify({ name: 'DYADRYN', short_name: 'DYADRYN', description: 'AI Persona Arena. Built from memory. Proven in battle.', start_url: '/', display: 'standalone', background_color: '#0C0E0F', theme_color: '#0C0E0F', icons: [{ src: '/assets/brand/favicon.svg', sizes: 'any', type: 'image/svg+xml' }, { src: '/assets/brand/icon-192.png', sizes: '192x192', type: 'image/png' }, { src: '/assets/brand/icon-512.png', sizes: '512x512', type: 'image/png' }] }, null, 2));
console.log(`built ${pages.length} pages → site/  (css ${cssHash})`);
