// Static site builder — zero runtime dependencies.  src/ → site/
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { icon, ICONS } from './icons.mjs';
import { generate as agentFiles, robots as robotsTxt, jsonld } from './agent-files.mjs';
import { MOVES, RES, SIGS, STANCES, ATTRS, MODES, ARCHETYPES, LEVELS } from './content.mjs';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const src = path.join(root, 'src'), out = path.join(root, 'site');
const SITE = JSON.parse(fs.readFileSync(path.join(root, 'site.config.json'), 'utf8'));
SITE.origin = (process.env.SITE_ORIGIN || SITE.origin).replace(/\/$/, ''); // deploy script sets this to the real origin


fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const cp = (a, b) => { fs.mkdirSync(path.dirname(b), { recursive: true }); fs.copyFileSync(a, b); };
const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap(e => e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]);

// assets
for (const f of walk(path.join(src, 'assets'))) cp(f, path.join(out, path.relative(src, f)));

// generated icon map for client-side rendering
fs.writeFileSync(path.join(src, 'js/icons.js'), `/* generated by scripts/build.mjs — do not edit */\nwindow.DY=window.DY||{};DY.icons=${JSON.stringify(Object.fromEntries(Object.keys(ICONS).map(k => [k, icon(k, 'i', 24)])))};\n`);


// css bundle (order matters) + js copy, with content hash for cache-busting
const cssFiles = ['base', 'components', 'hero', 'sections', 'pages', 'stage', 'duel', 'manga'].filter(n => fs.existsSync(path.join(src, 'css', n + '.css')));
const minCss = (t) => t.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\s+/g, ' ').replace(/\s*([{};,>])\s*/g, '$1').replace(/;}/g, '}').trim();
const css = minCss(cssFiles.map(n => fs.readFileSync(path.join(src, 'css', n + '.css'), 'utf8')).join('\n'));
const cssHash = crypto.createHash('md5').update(css).digest('hex').slice(0, 8);
fs.mkdirSync(path.join(out, 'css'), { recursive: true });
fs.writeFileSync(path.join(out, 'css/site.css'), css);


const KJ = JSON.parse(fs.readFileSync(path.join(root, 'scripts/vendor/kanji.json'), 'utf8'));
// {{kj:追跡|v}} -> inline SVG of the glyph outlines (v = vertical stack). Decorative, aria-hidden; no font dependency.
const kanji = (t, vert) => { let x = 0, y = 0, parts = []; for (const ch of t) { const g = KJ[ch]; if (!g) throw new Error('missing kanji ' + ch); parts.push(`<path transform="translate(${vert ? 0 : x} ${vert ? y : 0})" d="${g[1]}"/>`); if (vert) y += 1000; else x += g[0]; } const w = vert ? 1000 : x, h = vert ? y : 1000; return `<svg class="kj${vert ? ' kj--v' : ''}" viewBox="0 0 ${w} ${h}" aria-hidden="true" focusable="false" fill="currentColor">${parts.join('')}</svg>`; };
fs.writeFileSync(path.join(src, 'js/content.js'), `/* generated by scripts/build.mjs from scripts/content.mjs — do not edit */\nwindow.DY=window.DY||{};DY.MOVES=${JSON.stringify(MOVES)};DY.RES=${JSON.stringify(RES)};DY.SIGS=${JSON.stringify(SIGS)};DY.STANCES=${JSON.stringify(STANCES)};DY.ARCH=${JSON.stringify(ARCHETYPES)};DY.LEVELS=${JSON.stringify(LEVELS)};DY.KJ=${JSON.stringify(Object.fromEntries([...ARCHETYPES.map(a => a.kj), ...LEVELS.map(l => l.kj), ...'撃砕防空観圧変映癒滞印守反衝終封幕'.split('')].map(k => [k, kanji(k, false)])))};\n`);
const jsHashes = {};
for (const f of fs.readdirSync(path.join(src, 'js'))) {
  const buf = fs.readFileSync(path.join(src, 'js', f));
  jsHashes[f] = crypto.createHash('md5').update(buf).digest('hex').slice(0, 8);
  cp(path.join(src, 'js', f), path.join(out, 'js', f));
}
const decode = (t) => t.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#39;/g, "'");
const esc = (t) => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');

const LVG = {
  cold: '<path d="M28 6c12 0 20 9 20 22 0 14-8 24-20 28C16 52 8 42 8 28 8 15 16 6 28 6z" fill="currentColor" opacity=".9"/><path d="M20 26h6M30 26h6M28 34v6" stroke="#0C0E0F" stroke-width="2.4" stroke-linecap="round"/><path d="M4 12l6 3M52 12l-6 3M3 44l7-3M53 44l-7-3" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>',
  masked: '<path d="M28 6c12 0 20 9 20 22 0 14-8 24-20 28C16 52 8 42 8 28 8 15 16 6 28 6z" fill="currentColor" opacity=".9"/><path d="M8 26h40M9 33h38M11 40h34" stroke="#0C0E0F" stroke-width="3" opacity=".75"/><path d="M20 24l5 3M36 24l-5 3" stroke="#0C0E0F" stroke-width="2.4" stroke-linecap="round"/>',
  carry: '<path d="M28 6c12 0 20 9 20 22 0 14-8 24-20 28C16 52 8 42 8 28 8 15 16 6 28 6z" fill="currentColor" opacity=".9"/><path d="M30 6l-5 14 6 8-5 12 4 16" fill="none" stroke="#0C0E0F" stroke-width="2.4" stroke-linejoin="round"/><path d="M14 27q6-6 12 0q-6 5-12 0z" fill="#0C0E0F"/><circle cx="20" cy="27" r="2.2" fill="currentColor"/><path d="M36 26l7 2" stroke="#0C0E0F" stroke-width="2.4" stroke-linecap="round"/>',
  deep: '<path d="M26 6C15 7 8 16 8 28c0 14 8 24 18 28V6z" fill="currentColor" opacity=".9"/><path d="M32 6c10 1 16 10 16 22 0 10-4 20-12 25" fill="none" stroke="currentColor" stroke-width="2.6" stroke-linecap="round" stroke-dasharray="3 4"/><path d="M14 27q6-6 12 0q-6 5-12 0z" fill="#0C0E0F"/><circle cx="20" cy="27" r="2.2" fill="currentColor"/><circle cx="38" cy="27" r="4" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="38" cy="27" r="1.6" fill="currentColor"/><path d="M29 6v50" stroke="#0C0E0F" stroke-width="2"/>'
};
const GEN = {
  moves: () => MOVES.map((m, i) => `<article class="move rv" id="move-${m.k.toLowerCase()}" style="--d:${(i % 2) * 60}ms"><header><span class="mv-ico">${icon(m.ico, 'i', 36)}</span><div><h3>${m.name}</h3><span class="caps">${m.line}</span></div></header><p>${m.desc}</p><div class="chips"><span class="tag">Energy · ${m.energy}</span><span class="tag tag--oxide">${m.gain}</span><span class="tag tag--trace">${m.risk}</span></div><dl><div><dt>Best when</dt><dd>${m.when}</dd></div><div><dt>Watch out</dt><dd>${m.watch}</dd></div></dl></article>`).join(''),
  resources: () => RES.map(r => `<div class="res-row rv"><span class="res-ico">${icon(r.k, 'i', 28)}</span><div><h3>${r.name}</h3><p>${r.def}</p><p class="muted">${r.more}</p></div><span class="tag">${r.range}</span></div>`).join(''),
  signatures: () => SIGS.map((g, i) => `<li class="sig rv" style="--d:${(i % 4) * 50}ms"><span class="tag tag--trace">${g.tag}</span><h3>${g.name}</h3><p>${g.desc}</p><code>${g.id}</code></li>`).join(''),
  stances: () => STANCES.map(s => `<li class="rv"><h3>${s[0]}</h3><p><span class="up">▲ ${s[1]}</span><span class="dn">▼ ${s[2]}</span></p></li>`).join(''),
  attrs: () => ATTRS.map(a => `<li class="rv"><b>${a[0]}</b><span>${a[1]}</span></li>`).join(''),
  archetypes: () => ARCHETYPES.map((a, i) => `<article class="ac frame rv" style="--acc:${a.acc};--d:${(i % 2) * 60}ms" id="arch-${a.k}"><div class="ac-art"><img src="assets/art/face-${a.k}.webp" alt="" width="560" height="847" loading="lazy" decoding="async"><span class="ac-kj">{{kj:${a.kj}|v}}</span><span class="ac-no">0${i + 1}</span></div><div class="ac-b"><header><h3>${a.name}</h3><span class="caps">${a.kjr}</span></header><p class="ac-line">${a.line}</p><ul class="ac-w">${a.words.map(w => `<li>${w}</li>`).join('')}</ul><dl class="ac-d"><div><dt>How it plays</dt><dd>${a.plays}</dd></div><div><dt>Strong at</dt><dd>${a.strong}</dd></div><div><dt>Weak to</dt><dd>${a.weak}</dd></div><div><dt>Beat it by</dt><dd>${a.beat}</dd></div></dl><p class="ac-pick"><b>Pick it if:</b> ${a.pick}</p></div></article>`).join(''),
  levels: () => LEVELS.map((l, i) => `<label class="lv" style="--acc:${l.acc}"><input type="radio" name="df" value="${i}"${i === 0 ? ' checked' : ''}><span class="lv-c"><span class="lv-g"><svg viewBox="0 0 56 62" aria-hidden="true" focusable="false">${LVG[l.k]}</svg></span><span class="lv-t"><b>${l.name}</b><small>${l.line}</small><em>${l.who}</em></span><span class="lv-kj" aria-hidden="true">{{kj:${l.kj}}}</span><span class="lv-pips" aria-hidden="true">${[0, 1, 2, 3].map(n => `<i${n <= i ? ' class="on"' : ''}></i>`).join('')}</span></span></label>`).join(''),
  modes: () => MODES.map(m => `<article class="mode rv frame panel"><span class="tag">${m.tag}</span><h3>${m.name}</h3><p>${m.desc}</p></article>`).join('')
};

// partials
const partial = (name) => {
  for (const d of ['partials', 'partials/_gen']) { const p = path.join(src, d, name + '.html'); if (fs.existsSync(p)) return fs.readFileSync(p, 'utf8'); }
  throw new Error('missing partial ' + name);
};
let uid = 0;
function render(html, meta, depth = 0) {
  if (depth > 6) throw new Error('include depth');
  html = html.replace(/\{\{>\s*([\w-]+)\s*\}\}/g, (_, n) => render(partial(n).replaceAll('{{uid}}', 'u' + (++uid)), meta, depth + 1));
  html = html.replace(/\{\{gen:(\w+)\}\}/g, (_, n) => GEN[n]());
  html = html.replace(/\{\{kj:([^|}]+)(\|v)?\}\}/g, (_, t, v) => kanji(t, !!v));
  html = html.replace(/\{\{icon:([\w-]+)(?::(\d+))?\}\}/g, (_, n, s) => { if (!ICONS[n]) throw new Error('missing icon ' + n); return icon(n, 'i', s ? +s : 24); });
  html = html.replace(/\{\{cur:([\w-]+)\}\}/g, (_, n) => meta.active === n ? ' aria-current="page"' : '');
  html = html.replace(/\{\{earlyaccess\}\}/g, () => SITE.earlyAccessEndpoint
    ? `<form class="ea frame panel" id="eaForm" data-endpoint="${SITE.earlyAccessEndpoint}" novalidate><label for="eaMail" class="caps muted">Early access list</label><div class="ea-row"><input id="eaMail" name="email" type="email" autocomplete="email" required placeholder="you@example.com" aria-describedby="eaMsg"><button class="btn btn--primary" type="submit">Notify me</button></div><p id="eaMsg" class="muted" role="status" style="margin:.7rem 0 0;font-size:.9rem">One email when operator slots open. No lists sold. Unsubscribe any time.</p></form>`
    : '');
  html = html.replace(/\{\{contact\}\}/g, () => SITE.contactEmail ? `<a href="mailto:${SITE.contactEmail}">${SITE.contactEmail}</a>` : 'the contact address published at launch');
  html = html.replace(/\{\{css\}\}/g, 'css/site.css?v=' + cssHash);
  html = html.replace(/\{\{js:([\w.-]+)\}\}/g, (_, n) => `js/${n}?v=${jsHashes[n] ?? 'x'}`);
  html = html.replace(/\{\{site\.(\w+)\}\}/g, (_, k) => SITE[k] ?? '');
  html = html.replace(/\{\{pagescripts\}\}/g, () => (meta.scripts ?? []).map(n => `<script src="js/${n}?v=${jsHashes[n] ?? 'x'}" defer></script>`).join('\n'));
  html = html.replace(/\{\{(title|description|canonical|ogimage|bodyclass|active|jsonld|mdalt)\}\}/g, (_, k) => meta[k] ?? '');
  return html;
}

const pages = fs.readdirSync(path.join(src, 'pages')).filter(f => f.endsWith('.html'));
const urls = [], pageInfo = [];
for (const f of pages) {
  let raw = fs.readFileSync(path.join(src, 'pages', f), 'utf8');
  const m = raw.match(/^<!--meta\s*([\s\S]*?)-->\s*/);
  if (!m) throw new Error('page missing meta: ' + f);
  const meta = JSON.parse(m[1]);
  raw = raw.slice(m[0].length);
  const slug = f === 'index.html' ? '' : f;
  meta.canonical = SITE.origin + '/' + slug;
  meta.ogimage = SITE.origin + '/assets/brand/og-image.png';
  const faq = [...raw.matchAll(/<details[^>]*><summary><b>([\s\S]*?)<\/b><\/summary><div><p>([\s\S]*?)<\/p><\/div><\/details>/g)].map((x) => [x[1], x[2]].map((t) => decode(t.replace(/<[^>]+>/g, '')).trim()));
  const title0 = meta.title;
  meta.title = meta.title === 'DYADRYN' ? 'DYADRYN — Built from memory. Proven in battle. | AI Persona Arena' : meta.title + ' — DYADRYN';
  const pinfo = { file: f, slug, title: meta.title, description: meta.description, faq }; pageInfo.push(pinfo);
  meta.jsonld = jsonld(SITE.origin, pinfo); meta.mdalt = `<link rel="alternate" type="text/markdown" href="${f === 'index.html' ? 'index.md' : f.replace(/\.html$/, '.md')}">`;
  const full = render(`{{> head}}<body class="${meta.bodyclass ?? ''}">{{> header}}<main id="main">${raw}</main>{{> footer}}</body></html>`, meta);
  fs.writeFileSync(path.join(out, f), full);
  if (f !== '404.html') urls.push(SITE.origin + '/' + slug);
}

// robots (reserve rights: AI-training crawlers disallowed), sitemap, headers, manifest
// Training crawlers are disallowed (IP reserved); search/retrieval/agent user-agents are welcome (Content-Signal).
const TRAIN_BOTS = ['GPTBot', 'CCBot', 'anthropic-ai', 'ClaudeBot', 'Google-Extended', 'Applebot-Extended', 'Bytespider', 'Amazonbot', 'FacebookBot', 'meta-externalagent', 'cohere-ai', 'cohere-training-data-crawler', 'Diffbot', 'ImagesiftBot', 'omgili', 'omgilibot', 'PanguBot', 'Timpibot', 'VelenPublicWebCrawler', 'Kangaroo Bot'];
fs.writeFileSync(path.join(out, 'robots.txt'), robotsTxt(SITE.origin, TRAIN_BOTS));
fs.writeFileSync(path.join(out, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u => `  <url><loc>${u}</loc></url>`).join('\n')}\n</urlset>\n`);
fs.writeFileSync(path.join(out, '_headers'), `/*
  Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  tdm-reservation: 1
  tdm-policy: ${SITE.origin}/legal.html#rights

/assets/art/*
  Cache-Control: public, max-age=2592000
/assets/fonts/*
  Cache-Control: public, max-age=31536000, immutable
/css/*
  Cache-Control: public, max-age=31536000, immutable
/js/*
  Cache-Control: public, max-age=31536000, immutable
`);
fs.writeFileSync(path.join(out, 'manifest.webmanifest'), JSON.stringify({ name: 'DYADRYN', short_name: 'DYADRYN', description: 'AI Persona Arena. Built from memory. Proven in battle.', start_url: '/', display: 'standalone', background_color: '#0C0E0F', theme_color: '#0C0E0F', icons: [{ src: '/assets/brand/favicon.svg', sizes: 'any', type: 'image/svg+xml' }, { src: '/assets/brand/icon-192.png', sizes: '192x192', type: 'image/png' }, { src: '/assets/brand/icon-512.png', sizes: '512x512', type: 'image/png' }] }, null, 2));
agentFiles({ out, SITE, pages: pageInfo, origin: SITE.origin, worker: { openapi: path.join(root, 'worker/openapi.json') } });
console.log(`built ${pages.length} pages → site/  (css ${cssHash})`);
