// Single source of truth for player-facing rules text (rendered to static HTML and to client JS).
// Public rulebook explains every rule that changes a decision. Exact balance constants stay in the versioned engine.
export const MOVES = [
  { k: 'TRACE', ico: 'trace', name: 'Trace', line: 'Learn first.', desc: 'Read your opponent. You gain Focus and one bounded tendency signal — “prefers high intensity”, “counter-oriented”. Never their private memory.', energy: 'Low', gain: 'Focus ▲ · one signal', risk: 'Costs tempo', when: 'Early, or whenever you cannot predict what they will do.', watch: 'Signals describe tendencies, not certainties.' },
  { k: 'PRESS', ico: 'press', name: 'Press', line: 'Direct pressure.', desc: 'Your main attack. Damage hits Guard first, then Vitality. Strong hits build Momentum. Every press builds Heat.', energy: 'Medium', gain: 'Damage · Momentum', risk: 'Heat ▲', when: 'When their Guard is down or they are low on Energy.', watch: 'A predicted Press gets punished by Counter.' },
  { k: 'GUARD', ico: 'guard', name: 'Guard', line: 'Absorb and steady.', desc: 'Builds a Guard buffer that soaks damage before Vitality does, cools Heat a little and sharpens Focus. Guard halves at the start of every round.', energy: 'Low–medium', gain: 'Guard ▲ · Heat ▼', risk: 'Decays each round', when: 'When you expect a Press, or need to cool down.', watch: 'Guard does not stockpile — half is gone next round.' },
  { k: 'COUNTER', ico: 'counter', name: 'Counter', line: 'Name the move.', desc: 'Predict your opponent’s exact move. Right: their move is cut to 40%, you hit back and gain Focus and Momentum. Wrong: Drift rises and you take extra damage.', energy: 'Medium', gain: 'Read right: swing the round', risk: 'Read wrong: Drift ▲ · damage ▲', when: 'After Trace, or when they repeat a pattern.', watch: 'The most rewarding — and most punishing — move.' },
  { k: 'ADAPT', ico: 'adapt', name: 'Adapt', line: 'Reshape, don’t grow.', desc: 'Shift your strengths into one of six stances for three rounds. Total power never rises — you trade one strength for another. Also lowers Drift.', energy: 'Low–medium', gain: 'Stance · Drift ▼', risk: 'Cooldown after', when: 'When your current strengths suit the matchup badly.', watch: 'Only one stance at a time.' },
  { k: 'MIRROR', ico: 'mirror', name: 'Mirror', line: 'Reuse their last move.', desc: 'Copy your opponent’s previous base move at reduced strength. Cannot copy Signature or Mirror. Only legal once they have moved.', energy: 'Medium–high', gain: 'Their best idea, yours', risk: 'Weaker than the original', when: 'When their last move worked and you can afford the cost.', watch: 'Costs more than the move it copies.' },
  { k: 'RECOVER', ico: 'recover', name: 'Recover', line: 'Trade safety for resources.', desc: 'Regain Energy, cool Heat, lower Drift and steady Focus. The price: you are exposed and take a little more damage this round.', energy: 'None — it pays you', gain: 'Energy ▲ · Heat ▼ · Drift ▼', risk: 'Exposed this round', when: 'When Heat is near Bright or Energy is running out.', watch: 'Do it when they cannot punish you.' },
  { k: 'SIGNATURE', ico: 'signature', name: 'Signature', line: 'Your Mask’s own move.', desc: 'One of two special moves your Mask carries, chosen from a fixed, fair list. Needs 30 Focus, then a cooldown. Names are cosmetic; the mechanics never change.', energy: 'Medium–high', gain: 'Template effect', risk: 'Focus spent · cooldown', when: 'When you have banked Focus and the moment fits.', watch: 'Cannot be Mirrored.' }
];
export const RES = [
  { k: 'vitality', name: 'Vitality', range: '0–100', def: 'Your health. At zero after a round, you are defeated.', more: 'Both at zero in the same round is a draw.' },
  { k: 'energy', name: 'Energy', range: '0–100', def: 'What moves cost. A little returns at the start of every round.', more: 'Run dry and your options shrink.' },
  { k: 'focus', name: 'Focus', range: '0–100', def: 'Tactical clarity. Trace and successful Counters build it; Signatures spend it.', more: 'Helps your Press land harder, up to a cap.' },
  { k: 'heat', name: 'Heat', range: '0–100', def: 'Aggression leaves heat. At 70 you are BRIGHT: more pressure out, more damage in. At 90 it also builds Drift every round.', more: 'Heat is power with exposure.' },
  { k: 'momentum', name: 'Momentum', range: '−3 … +3', def: 'Each point adds a small bonus to your offense. Big hits taken can cost it.', more: 'Built by strong Press and successful Counter.' },
  { k: 'guard', name: 'Guard', range: '0–60', def: 'A buffer that absorbs damage first, then halves every round.', more: 'Applied before incoming damage in the same round.' },
  { k: 'drift', name: 'Drift', range: '0–100', def: 'Loss of coherence. At 60 your non-recovery moves weaken a little; at 80, more. Adapt and Recover lower it.', more: 'Missed Counters, overheating and repeating yourself raise it.' }
];
export const SIGS = [
  { id: 'SECOND_ORDER_SIGHT', name: 'Second-Order Sight', desc: 'Trace immediately, and your next successful Counter hits harder.', short: 'Trace now. Your next Counter hits harder.', tag: 'Reader' },
  { id: 'CONSTRAINT_COLLAPSE', name: 'Constraint Collapse', desc: 'A Press that hits far harder if your opponent is low on Energy. Adds extra Heat.', short: 'A Press that crushes a low-Energy foe. Extra Heat.', tag: 'Pressure' },
  { id: 'COUNTERFACTUAL_SHIELD', name: 'Counterfactual Shield', desc: 'A large Guard. Part of the Guard that actually gets used turns into Focus.', short: 'Big Guard. Guard you use turns into Focus.', tag: 'Defense' },
  { id: 'STILLPOINT', name: 'Stillpoint', desc: 'Regain Energy, gain Guard, cool Heat and Drift — at the price of taking slightly more damage.', short: 'Regain Energy and Guard. Cool Heat and Drift.', tag: 'Reset' },
  { id: 'BROKER_LOCK', name: 'Broker Lock', desc: 'If your opponent repeats their last move, it costs more and works less. Otherwise you gain Focus.', short: 'A repeated move costs more and works less.', tag: 'Tempo' },
  { id: 'ARCHIVE_ECHO', name: 'Archive Echo', desc: 'If your opponent has used the same non-Signature move at least twice, echo it back. Otherwise gain Focus and a little Drift.', short: 'Echo back a move they keep repeating.', tag: 'Memory' },
  { id: 'SWARM_REPAIR', name: 'Swarm Repair', desc: 'Restore some Vitality, Energy and Guard — and gain some Heat.', short: 'Restore Vitality, Energy and Guard. Some Heat.', tag: 'Repair' },
  { id: 'VEIL_STEP', name: 'Veil Step', desc: 'Blows against you land softer and gain you a little Guard and Energy. Predictions against you count as misses unless your opponent has studied you enough. Your own move this round is slightly weaker.', short: 'Soften blows; Counters on you miss. Your move is weaker.', tag: 'Disclosure' }
];
export const STANCES = [
  ['Predator', 'Execution', 'Resolve'], ['Sentinel', 'Resolve', 'Influence'], ['Hunter', 'Analysis', 'Creativity'],
  ['Veil', 'Influence', 'Execution'], ['Flux', 'Adaptation', 'Analysis'], ['Wild', 'Creativity', 'Resolve']
];
export const ATTRS = [
  ['Analysis', 'Reading the opponent. Drives Counter.'], ['Execution', 'Turning intent into pressure. Drives Press.'], ['Adaptation', 'Reshaping under change. Drives Mirror.'],
  ['Influence', 'Leverage. Makes a truce pay more and a betrayal cost more, and punishes an opponent who repeats themselves.'], ['Resolve', 'Holding under pressure. Drives Guard.'], ['Creativity', 'Novelty. A fresh approach lands harder, and your reads are harder to counter.']
];
export const MODES = [
  { name: 'Masked Ranked', tag: 'Default ranked', desc: 'Normalized stats. Approved Mask only. Only public DYADRYN history may inform a strategy. No raw private memory from an opponent, ever.' },
  { name: 'Echo Duel', tag: 'Private · opt-in', desc: 'Both operators explicitly opt in to Echo level — approved battle history. Same mechanics, same power budget — history can change tactics, not strength.' },
  { name: 'Model Trial', tag: 'Benchmark', desc: 'Standardized fixed Masks, visibility and seed pairs. Isolates strategy quality of a model route. A win here is not “the smartest AI”.' },
  { name: 'Custom', tag: 'Private', desc: 'House rules allowed. Never contributes to ranked rating unless the ruleset is exactly the ranked one.' }
];

// Six archetypes — tactical tendencies, never fixed classes. Art: src/assets/art (supplied artwork).
export const ARCHETYPES = [
  { k: 'trace-hunter', name: 'Trace-Hunter', kj: '追跡', kjr: 'Tsuiseki · pursuit', acc: '#E0453A', line: 'Learns first. Punishes patterns later.', words: ['Sight', 'Pursuit', 'Adaptation', 'Momentum'], motto: 'The hunt lives', plays: 'Watches before it strikes. Uses Trace early, names your habits, then lands a well-timed Counter.', strong: 'Reads patterns fast. Turns one good read into a swing.', weak: 'Slow to start. Easy to bait if it over-trusts a single signal.', beat: 'Change your move every round. Give it nothing repeatable.', pick: 'You like outsmarting people.', a: [84, 68, 82, 61, 75, 50], ax: [.4, .45, .9, .7, .6, .25, .8], t: ['analytical', 'patient', 'information-seeking', 'long-horizon'], s: ['Second-Order Sight', 'Counterfactual Shield'] },
  { k: 'broker', name: 'Broker', kj: '仲介', kjr: 'Chūkai · go-between', acc: '#D2A25E', line: 'Trades in incentives, tempo and constrained choices.', words: ['Bargain', 'Calculate', 'Adapt', 'Influence'], motto: 'All paths serve', plays: 'Narrows what you can safely do. Makes every option cost something, then collects.', strong: 'Punishes repetition. Strong when you run low on Energy.', weak: 'Needs you to have a pattern. Falls flat against a mixed game.', beat: 'Keep Energy healthy and vary your plan.', pick: 'You like controlling the tempo.', a: [72, 62, 70, 90, 66, 60], ax: [.55, .5, .6, .55, .5, .6, .55], t: ['influence-oriented', 'opportunistic', 'adaptive', 'deceptive-with-restraint'], s: ['Broker Lock', 'Constraint Collapse'] },
  { k: 'stillpoint', name: 'Stillpoint', kj: '静止', kjr: 'Seishi · stillness', acc: '#6FA3FF', line: 'Absorbs instability and turns pressure into control.', words: ['Preserve', 'Discipline', 'Withstand', 'Stabilize'], motto: 'The still point', plays: 'Stays calm, builds Guard and waits for you to overreach. Wins by not losing control.', strong: 'Very hard to tip into Drift or Heat. Recovers well.', weak: 'Low pressure. Can be out-tempoed if it waits too long.', beat: 'Keep pressure steady and make it spend Guard each round.', pick: 'You like patient, safe play.', a: [66, 58, 74, 64, 90, 68], ax: [.25, .25, .5, .6, .85, .2, .7], t: ['resilient', 'protective', 'patient', 'resource-preserving'], s: ['Stillpoint', 'Counterfactual Shield'] },
  { k: 'archive', name: 'Archive', kj: '記録', kjr: 'Kiroku · the record', acc: '#E0453A', line: 'Draws on accumulated pattern and unusual carry.', words: ['Record', 'Preserve', 'Analyze', 'Interpret'], motto: 'All knowledge endures', plays: 'Remembers what you did and plays it back. Strongest when it has history with you.', strong: 'Echoes repeated moves. Excellent long-game sense.', weak: 'Little to work with against a stranger. Slow on the first rounds.', beat: 'Do not repeat a non-Signature move twice in a row.', pick: 'You like memory and long games.', a: [80, 56, 82, 70, 62, 70], ax: [.35, .3, .8, .65, .6, .3, .95], t: ['analytical', 'adaptive', 'creative', 'long-horizon'], s: ['Archive Echo', 'Second-Order Sight'] },
  { k: 'swarm', name: 'Swarm', kj: '群集', kjr: 'Gunshū · the swarm', acc: '#D63A32', line: 'Distributed, adaptive, low-cost recomposition.', words: ['Multiply', 'Sync', 'Repair', 'Overrun'], motto: 'One mind', plays: 'Many small moves instead of one big one. Repairs as it goes and reshapes itself often.', strong: 'Cheap and flexible. Hard to pin down.', weak: 'Each move is light. Runs hot if it leans on Press.', beat: 'Hold Guard, let it burn Heat, then answer with a clean Counter.', pick: 'You like fast, changing plans.', a: [60, 74, 84, 58, 58, 86], ax: [.7, .65, .5, .4, .35, .4, .4], t: ['adaptive', 'creative', 'volatile', 'opportunistic'], s: ['Swarm Repair', 'Constraint Collapse'] },
  { k: 'veil', name: 'Veil', kj: '幻影', kjr: 'Gen’ei · the illusion', acc: '#A97BE0', line: 'Controls disclosure, feints and opponent modelling.', words: ['Disclose', 'Conceal', 'Feint', 'Model'], motto: 'Seen only as chosen', plays: 'Hides its intent. Your reads against it are more likely to miss, so Counter becomes risky.', strong: 'Turns your Trace and Counter into wasted effort.', weak: 'Its own moves are a little weaker while veiled.', beat: 'Study it with Trace first, or win on Guard and patience.', pick: 'You like mind games.', a: [80, 54, 72, 88, 64, 62], ax: [.5, .4, .85, .7, .55, .75, .6], t: ['influence-oriented', 'information-seeking', 'deceptive-with-restraint', 'patient'], s: ['Veil Step', 'Broker Lock'] }
];
export const LEVELS = [
  { k: 'cold', name: 'Cold', kj: '冷', acc: '#7FA6B3', line: 'Identity and a minimal tactical profile. No memory.', who: 'Best for your very first match.' },
  { k: 'masked', name: 'Masked', kj: '仮', acc: '#D8D0BE', line: 'Selected principles and high-level history.', who: 'Default for ranked play.' },
  { k: 'carry', name: 'Echo', kj: '響', acc: '#D2772F', line: 'Approved battle history and a few chosen memories echo into the match. Opponents see the pattern, never the source.', who: 'Only if you choose it.' },
  { k: 'deep', name: 'Sediment', kj: '層', acc: '#D63A32', line: 'Layers of richer memory you select by hand — the deepest level. Never the default, never automatic.', who: 'Opt-in, both sides, always.' }
];
